apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-manager
  labels:
    app: call-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: call-manager
  template:
    metadata:
      labels:
        app: call-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2112"
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: call-manager
          image: call-manager-image
          command:
            - '/app/call-manager'
          args:
            - '-rabbit_addr'
            - 'amqp://guest:guest@rabbitmq.voipbin.net:5672'
            - '-rabbit_queue_arievent'
            - 'asterisk_ari_event'
            - '-rabbit_queue_arirequest'
            - 'asterisk_ari_request'
            - '-prom_endpoint'
            - '/metrics'
            - '-prom_listen_addr'
            - ':2112'
          ports:
            - name: metrics
              protocol: "TCP"
              containerPort: 2112
          resources:
            limits:
              cpu: "10m"
              memory: "60M"
