apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-manager
  labels:
    app: call-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-manager
  template:
    metadata:
      labels:
        app: call-manager
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: call-manager
          image: call-manager-image
          command:
            - '/app/call-manager'
          args:
            - '-rabbit_addr'
            - 'amqp://guest:guest@rabbitmq.voipbin.net:5672'
            - '-rabbit_queue_ari'
            - 'asterisk_ari_event'
          resources:
            limits:
              cpu: "5m"
              memory: "60M"
