apiVersion: v1
kind: Service
metadata:
  name: api-manager
  # annotations:
  #   cloud.google.com/load-balancer-type: "Internal"

spec:
  type: NodePort
  selector:
    app: api-manager
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
